

//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class hashtag
{

    public int id { get; set; }

    public int official_route_id { get; set; }

    public int private_route_id { get; set; }

    public string hashtag_name { get; set; }



    public virtual Home Home { get; set; }

    public virtual private_route private_route { get; set; }

}


public partial class Home
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Home()
    {

        this.hashtags = new HashSet<hashtag>();

        this.official_route_comment = new HashSet<official_route_comment>();

        this.official_route_data = new HashSet<official_route_data>();

        this.user_favorite = new HashSet<user_favorite>();

    }


    public int id { get; set; }

    public string hname { get; set; }

    public string hdescription { get; set; }

    public string hrank { get; set; }

    public Nullable<decimal> hdistance { get; set; }

    public string himg { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<hashtag> hashtags { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<official_route_comment> official_route_comment { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<official_route_data> official_route_data { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<user_favorite> user_favorite { get; set; }

}


public partial class official_route_comment
{

    public int id { get; set; }

    public int article_title_id { get; set; }

    public int comment_user_id { get; set; }

    public Nullable<decimal> all_star_summary { get; set; }

    public int user_give_star_num { get; set; }

    public string comment { get; set; }

    public Nullable<System.DateTime> datetime { get; set; }



    public virtual Home Home { get; set; }

    public virtual user user { get; set; }

}


public partial class official_route_data
{

    public int id { get; set; }

    public string official_data_catalog { get; set; }

    public string official_data_img { get; set; }

    public string official_data_img_info { get; set; }

    public string official_data_content { get; set; }

    public int home_id { get; set; }



    public virtual Home Home { get; set; }

}


public partial class order
{

    public int id { get; set; }

    public int user_id { get; set; }

    public string user_name { get; set; }

    public string product_name { get; set; }

    public string product_img { get; set; }

    public Nullable<int> product_price { get; set; }

    public Nullable<int> order_num { get; set; }

    public Nullable<int> order_price_total { get; set; }

    public string order_date { get; set; }

    public string go_date { get; set; }

    public string order_pay { get; set; }



    public virtual user user { get; set; }

}


public partial class private_route
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public private_route()
    {

        this.hashtags = new HashSet<hashtag>();

        this.private_route_comment = new HashSet<private_route_comment>();

        this.user_favorite = new HashSet<user_favorite>();

    }


    public int id { get; set; }

    public int user_id { get; set; }

    public string article_title { get; set; }

    public Nullable<int> article_img_id { get; set; }

    public string article_img_info { get; set; }

    public string article_context { get; set; }

    public Nullable<System.DateTime> datetime { get; set; }

    public Nullable<int> fav_num { get; set; }

    public Nullable<int> seem_num { get; set; }

    public Nullable<int> star_num_sum { get; set; }

    public Nullable<int> sum_people_give_star { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<hashtag> hashtags { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<private_route_comment> private_route_comment { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<user_favorite> user_favorite { get; set; }

}


public partial class private_route_comment
{

    public int id { get; set; }

    public int article_title_id { get; set; }

    public int comment_user_id { get; set; }

    public int user_give_star_num { get; set; }

    public string comment { get; set; }

    public System.DateTime datetime { get; set; }



    public virtual private_route private_route { get; set; }

    public virtual user user { get; set; }

}


public partial class product
{

    public int id { get; set; }

    public string product_name { get; set; }

    public int product_price { get; set; }

    public string product_img { get; set; }

    public Nullable<int> product_num { get; set; }

}


public partial class user
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {

        this.official_route_comment = new HashSet<official_route_comment>();

        this.orders = new HashSet<order>();

        this.private_route_comment = new HashSet<private_route_comment>();

        this.user_favorite = new HashSet<user_favorite>();

    }


    public int id { get; set; }

    public string username { get; set; }

    public Nullable<System.DateTime> created_at { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public Nullable<System.DateTime> birthday { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<official_route_comment> official_route_comment { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<order> orders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<private_route_comment> private_route_comment { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<user_favorite> user_favorite { get; set; }

}


public partial class user_favorite
{

    public int id { get; set; }

    public int user_fav_id { get; set; }

    public int private_route_id { get; set; }

    public int official_route_id { get; set; }

    public System.DateTime datetime { get; set; }



    public virtual Home Home { get; set; }

    public virtual private_route private_route { get; set; }

    public virtual user user { get; set; }

}

