
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace bike_web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class official_route_data
{

    public int id { get; set; }

    public string official_data_catalog { get; set; }

    public string official_data_img { get; set; }

    public string official_data_img_info { get; set; }

    public string official_data_content { get; set; }

    public int home_id { get; set; }



    public virtual Home Home { get; set; }

}

}
