
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace bike_web.Models
{

using System;
    using System.Collections.Generic;
    
public partial class order
{

    public int id { get; set; }

    public int user_id { get; set; }

    public string user_name { get; set; }

    public string product_name { get; set; }

    public string product_img { get; set; }

    public Nullable<int> product_price { get; set; }

    public Nullable<int> order_num { get; set; }

    public Nullable<int> order_price_total { get; set; }

    public string order_date { get; set; }

    public string go_date { get; set; }

    public string order_pay { get; set; }



    public virtual user user { get; set; }

}

}
