//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bike_web.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        public int id { get; set; }

        [Required(ErrorMessage = "品名不可為空白")]
        [DisplayName("品名")]
        public string product_name { get; set; }

        [DisplayName("優惠價")]
        public int product_price { get; set; }


        [DisplayName("圖示")]
        public string product_img { get; set; }

        [DisplayName("名額")]
        public Nullable<int> product_num { get; set; }
    }
}
