//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bike_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_favorite
    {
        public int id { get; set; }
        public int user_fav_id { get; set; }
        public int private_route_id { get; set; }
        public int official_route_id { get; set; }
        public System.DateTime datetime { get; set; }
    
        public virtual official_route_data official_route_data { get; set; }
        public virtual private_route private_route { get; set; }
        public virtual user user { get; set; }
    }
}
